-- BoiledStream Supabase setup
-- À exécuter dans Supabase > SQL Editor > New query.

create or replace function public.clean_display_name(value text)
returns text
language sql
immutable
as $$
  select coalesce(
    nullif(
      left(
        btrim(
          regexp_replace(
            regexp_replace(coalesce(value, ''), '[^A-Za-z0-9 _-]+', '', 'g'),
            '[[:space:]]+',
            ' ',
            'g'
          )
        ),
        40
      ),
      ''
    ),
    'Utilisateur'
  );
$$;

create or replace function public.is_valid_display_name(value text)
returns boolean
language sql
immutable
as $$
  select value = public.clean_display_name(value)
    and char_length(value) between 1 and 40;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (
    char_length(display_name) between 1 and 40
    and public.is_valid_display_name(display_name)
  ),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.profiles
  add column if not exists avatar_url text;

update public.profiles
set display_name = public.clean_display_name(display_name)
where not public.is_valid_display_name(display_name);

alter table public.profiles
  drop constraint if exists profiles_display_name_plain_check;

alter table public.profiles
  add constraint profiles_display_name_plain_check
  check (public.is_valid_display_name(display_name));

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users
  drop constraint if exists admin_users_user_id_fkey;

alter table public.admin_users
  add constraint admin_users_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  video_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ratings (
  video_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  score smallint not null check (score between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (video_id, user_id)
);

create index if not exists comments_video_id_created_at_idx
  on public.comments (video_id, created_at desc);

create index if not exists ratings_video_id_idx
  on public.ratings (video_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    public.clean_display_name(
      coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.create_profile_for_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

drop trigger if exists ratings_set_updated_at on public.ratings;
create trigger ratings_set_updated_at
before update on public.ratings
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.admin_users enable row level security;
alter table public.comments enable row level security;
alter table public.ratings enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.profiles, public.admin_users, public.comments, public.ratings to anon;
grant select, insert, update, delete on public.profiles, public.comments, public.ratings to authenticated;
grant select on public.admin_users to authenticated;
revoke insert, update, delete on public.admin_users from anon, authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Profiles are readable by everyone" on public.profiles;
create policy "Profiles are readable by everyone"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "Admin markers are readable by everyone" on public.admin_users;
create policy "Admin markers are readable by everyone"
on public.admin_users for select
to anon, authenticated
using (true);

drop policy if exists "Comments are readable by everyone" on public.comments;
create policy "Comments are readable by everyone"
on public.comments for select
to anon, authenticated
using (true);

drop policy if exists "Users can create their own comments" on public.comments;
create policy "Users can create their own comments"
on public.comments for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own comments" on public.comments;
create policy "Users can update their own comments"
on public.comments for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own comments" on public.comments;
create policy "Users can delete their own comments"
on public.comments for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Ratings are readable by everyone" on public.ratings;
create policy "Ratings are readable by everyone"
on public.ratings for select
to anon, authenticated
using (true);

drop policy if exists "Users can create their own ratings" on public.ratings;
create policy "Users can create their own ratings"
on public.ratings for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own ratings" on public.ratings;
create policy "Users can update their own ratings"
on public.ratings for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own ratings" on public.ratings;
create policy "Users can delete their own ratings"
on public.ratings for delete
to authenticated
using ((select auth.uid()) = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

grant select on storage.buckets to anon, authenticated;
grant select on storage.objects to anon;
grant select, insert, update, delete on storage.objects to authenticated;

drop policy if exists "Avatar images are publicly readable" on storage.objects;
create policy "Avatar images are publicly readable"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'avatars');

drop policy if exists "Users can upload their own avatar" on storage.objects;
create policy "Users can upload their own avatar"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users can update their own avatar" on storage.objects;
create policy "Users can update their own avatar"
on storage.objects for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Users can delete their own avatar" on storage.objects;
create policy "Users can delete their own avatar"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

notify pgrst, 'reload schema';

select id, name, public, file_size_limit, allowed_mime_types
from storage.buckets
where id = 'avatars';
